server:
  port: 8000

spring:
  application:
    name: taskstream

  datasource:
    url: jdbc:h2:mem:taskstreamdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
